In [1]:
import pandas as pd

from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

In [84]:
# Hardcoded list of known 70+ point games

recent_high_scoring_games = [
    {"PLAYER_NAME": "Kobe Bryant", "PLAYER_ID": 977, "GAME_DATE": "2006-01-22"},
    {"PLAYER_NAME": "Devin Booker", "PLAYER_ID": 1626164, "GAME_DATE": "2017-03-24"},
    {"PLAYER_NAME": "Donovan Mitchell", "PLAYER_ID": 1628378, "GAME_DATE": "2023-01-02"},
    {"PLAYER_NAME": "Damian Lillard", "PLAYER_ID": 203081, "GAME_DATE": "2023-02-26"},
    {"PLAYER_NAME": "Joel Embiid", "PLAYER_ID": 203954, "GAME_DATE": "2024-01-22"},
    {"PLAYER_NAME": "Luka Dončić", "PLAYER_ID": 1629029, "GAME_DATE": "2024-01-26"},
    {"PLAYER_NAME": "Bam Adebayo", "PLAYER_ID": 1628389, "GAME_DATE": "2026-03-10"}
]

## ***Pull these 70 Point Games from the API into 1 DataFrame***

In [131]:
seasons = ['2005-06', '2016-17', '2022-23','2022-23', '2023-24', '2023-24', '2025-26']

date = ["Jan 22, 2006", "Mar 24, 2017", "Jan 02, 2023", "Feb 26, 2023", "Jan 22, 2024", "Jan 26, 2024", "Mar 10, 2026"]

all_dfs = []

for game in recent_high_scoring_games:  # devin and donovan missing??
    gamelog = playergamelog.PlayerGameLog(player_id=game['PLAYER_ID'], 
                            season = seasons[recent_high_scoring_games.index(game)], 
                            season_type_all_star = 'Regular Season')

    df = gamelog.get_data_frames()[0]

    df = df[df["GAME_DATE"] == date[recent_high_scoring_games.index(game)]]
    df['GAME_DATE'] = game["GAME_DATE"]
    df['Player'] = game['PLAYER_NAME']

    all_dfs.append(df)

all_dfs = pd.concat(all_dfs, ignore_index=True)

all_dfs

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,Player
0,22005,977,0020500591,2006-01-22,LAL vs. TOR,W,42,28,46,0.609,...,6,2,3,1,3,1,81,25,0,Kobe Bryant
1,22016,1626164,0021601076,2017-03-24,PHX @ BOS,L,45,21,40,0.525,...,8,6,3,1,5,3,70,-6,1,Devin Booker
2,22022,1628378,0022200552,2023-01-02,CLE vs. CHI,W,50,22,34,0.647,...,8,11,0,1,4,3,71,19,1,Donovan Mitchell
3,22022,203081,0022200917,2023-02-26,POR vs. HOU,W,39,22,38,0.579,...,6,6,0,0,2,0,71,21,1,Damian Lillard
4,22023,203954,0022300608,2024-01-22,PHI vs. SAS,W,37,24,41,0.585,...,18,5,1,1,1,2,70,11,1,Joel Embiid
5,22023,1629029,0022300634,2024-01-26,DAL @ ATL,W,45,25,33,0.758,...,10,7,1,0,4,1,73,13,1,Luka Dončić
6,22025,1628389,0022500938,2026-03-10,MIA vs. WAS,W,42,20,43,0.465,...,9,3,2,2,5,3,83,20,1,Bam Adebayo

# Since the database only goes back to 1999, we need to import the older 70 point games recorded

## ***Import the Historical Games.csv Dataset and concatenate it with the above DataFrame***

In [125]:
dfold = pd.read_csv("Historical Games.csv")

dfold

             Player   GAME_DATE       MATCHUP  PTS  FG_PCT WL
0      Elgin Baylor  1960-11-15   LAL vs. NYK   71   0.583  W
1  Wilt Chamberlain  1962-03-02   GSW vs. LAL   78   0.500  L
2  Wilt Chamberlain  1963-03-10   GSW vs. CHI   73   0.604  W
3  Wilt Chamberlain  1961-12-08   GSW vs. NYK  100   0.571  W
4  Wilt Chamberlain  1961-01-13  GSW vs. LAL    72   0.604  L
5  Wilt Chamberlain  1962-11-03    GSW vs NYK   73   0.674  W
6  Wilt Chamberlain  1962-11-16   GSW vs. SYC   70   0.711  L
7    David Thompson  1978-04-09   DET vs. DEN   73   0.737  L
8    David Robinson  1994-04-24   SAS vs. LAC   71   0.634  W

In [ ]:
# Combine into one DataFrame

all_stats = pd.concat([all_dfs, dfold], ignore_index=True)

all_stats

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,Player
0,22005,977.0,0020500591,2006-01-22,LAL vs. TOR,W,42.0,28.0,46.0,0.609,...,6.0,2.0,3.0,1.0,3.0,1.0,81,25.0,0.0,Kobe Bryant
1,22016,1626164.0,0021601076,2017-03-24,PHX @ BOS,L,45.0,21.0,40.0,0.525,...,8.0,6.0,3.0,1.0,5.0,3.0,70,-6.0,1.0,Devin Booker
2,22022,1628378.0,0022200552,2023-01-02,CLE vs. CHI,W,50.0,22.0,34.0,0.647,...,8.0,11.0,0.0,1.0,4.0,3.0,71,19.0,1.0,Donovan Mitchell
3,22022,203081.0,0022200917,2023-02-26,POR vs. HOU,W,39.0,22.0,38.0,0.579,...,6.0,6.0,0.0,0.0,2.0,0.0,71,21.0,1.0,Damian Lillard
4,22023,203954.0,0022300608,2024-01-22,PHI vs. SAS,W,37.0,24.0,41.0,0.585,...,18.0,5.0,1.0,1.0,1.0,2.0,70,11.0,1.0,Joel Embiid
5,22023,1629029.0,0022300634,2024-01-26,DAL @ ATL,W,45.0,25.0,33.0,0.758,...,10.0,7.0,1.0,0.0,4.0,1.0,73,13.0,1.0,Luka Dončić
6,22025,1628389.0,0022500938,2026-03-10,MIA vs. WAS,W,42.0,20.0,43.0,0.465,...,9.0,3.0,2.0,2.0,5.0,3.0,83,20.0,1.0,Bam Adebayo
7,NaN,NaN,NaN,1960-11-15,LAL vs. NYK,W,NaN,NaN,NaN,0.583,...,NaN,NaN,NaN,NaN,NaN,NaN,71,NaN,NaN,Elgin Baylor
8,NaN,NaN,NaN,1962-03-02,GSW vs. LAL,L,NaN,NaN,NaN,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,78,NaN,NaN,Wilt Chamberlain
9,NaN,NaN,NaN,1963-03-10,GSW vs. CHI,W,NaN,NaN,NaN,0.604,...,NaN,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,Wilt Chamberlain
10,NaN,NaN,NaN,1961-12-08,GSW vs. NYK,W,NaN,NaN,NaN,0.571,...,NaN,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,Wilt Chamberlain
11,NaN,NaN,NaN,1961-01-13,GSW vs. LAL,L,NaN,NaN,NaN,0.604,...,NaN,NaN,NaN,NaN,NaN,NaN,72,NaN,NaN,Wilt Chamberlain
12,NaN,NaN,NaN,1962-11-03,GSW vs NYK,W,NaN,NaN,NaN,0.674,...,NaN,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,Wilt Chamberlain
13,NaN,NaN,NaN,1962-11-16,GSW vs. SYC,L,NaN,NaN,NaN,0.711,...,NaN,NaN,NaN,NaN,NaN,NaN,70,NaN,NaN,Wilt Chamberlain
14,NaN,NaN,NaN,1978-04-09,DET vs. DEN,L,NaN,NaN,NaN,0.737,...,NaN,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,David Thompson
15,NaN,NaN,NaN,1994-04-24,SAS vs. LAC,W,NaN,NaN,NaN,0.634,...,NaN,NaN,NaN,NaN,NaN,NaN,71,NaN,NaN,David Robinson

## ***Create a "TEAM" column by using string manipulation on the "MATCHUP" column***

In [133]:
all_stats['TEAM'] = all_stats['MATCHUP'].str[:3]

all_stats

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,Player,TEAM
0,22005,977.0,0020500591,2006-01-22,LAL vs. TOR,W,42.0,28.0,46.0,0.609,...,2.0,3.0,1.0,3.0,1.0,81,25.0,0.0,Kobe Bryant,LAL
1,22016,1626164.0,0021601076,2017-03-24,PHX @ BOS,L,45.0,21.0,40.0,0.525,...,6.0,3.0,1.0,5.0,3.0,70,-6.0,1.0,Devin Booker,PHX
2,22022,1628378.0,0022200552,2023-01-02,CLE vs. CHI,W,50.0,22.0,34.0,0.647,...,11.0,0.0,1.0,4.0,3.0,71,19.0,1.0,Donovan Mitchell,CLE
3,22022,203081.0,0022200917,2023-02-26,POR vs. HOU,W,39.0,22.0,38.0,0.579,...,6.0,0.0,0.0,2.0,0.0,71,21.0,1.0,Damian Lillard,POR
4,22023,203954.0,0022300608,2024-01-22,PHI vs. SAS,W,37.0,24.0,41.0,0.585,...,5.0,1.0,1.0,1.0,2.0,70,11.0,1.0,Joel Embiid,PHI
5,22023,1629029.0,0022300634,2024-01-26,DAL @ ATL,W,45.0,25.0,33.0,0.758,...,7.0,1.0,0.0,4.0,1.0,73,13.0,1.0,Luka Dončić,DAL
6,22025,1628389.0,0022500938,2026-03-10,MIA vs. WAS,W,42.0,20.0,43.0,0.465,...,3.0,2.0,2.0,5.0,3.0,83,20.0,1.0,Bam Adebayo,MIA
7,NaN,NaN,NaN,1960-11-15,LAL vs. NYK,W,NaN,NaN,NaN,0.583,...,NaN,NaN,NaN,NaN,NaN,71,NaN,NaN,Elgin Baylor,LAL
8,NaN,NaN,NaN,1962-03-02,GSW vs. LAL,L,NaN,NaN,NaN,0.500,...,NaN,NaN,NaN,NaN,NaN,78,NaN,NaN,Wilt Chamberlain,GSW
9,NaN,NaN,NaN,1963-03-10,GSW vs. CHI,W,NaN,NaN,NaN,0.604,...,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,Wilt Chamberlain,GSW
10,NaN,NaN,NaN,1961-12-08,GSW vs. NYK,W,NaN,NaN,NaN,0.571,...,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,Wilt Chamberlain,GSW
11,NaN,NaN,NaN,1961-01-13,GSW vs. LAL,L,NaN,NaN,NaN,0.604,...,NaN,NaN,NaN,NaN,NaN,72,NaN,NaN,Wilt Chamberlain,GSW
12,NaN,NaN,NaN,1962-11-03,GSW vs NYK,W,NaN,NaN,NaN,0.674,...,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,Wilt Chamberlain,GSW
13,NaN,NaN,NaN,1962-11-16,GSW vs. SYC,L,NaN,NaN,NaN,0.711,...,NaN,NaN,NaN,NaN,NaN,70,NaN,NaN,Wilt Chamberlain,GSW
14,NaN,NaN,NaN,1978-04-09,DET vs. DEN,L,NaN,NaN,NaN,0.737,...,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,David Thompson,DET
15,NaN,NaN,NaN,1994-04-24,SAS vs. LAC,W,NaN,NaN,NaN,0.634,...,NaN,NaN,NaN,NaN,NaN,71,NaN,NaN,David Robinson,SAS

## ***Given the average number of possessions per decade, create a PTS (NORMALIZED) column to account for the different time peroids the players played in***

In [ ]:
# The following is the average number of possessions per decade

possessions_by_decade = {1950: 93, 
                         1960: 115,
                         1970: 106, 
                         1980: 103, 
                         1990: 94,
                         2000: 91,
                         2010: 96, 
                         2020: 99}

In [ ]:
# Normalize points by possessions

for i in all_stats:
    all_stats['DECADE'] = (all_stats['GAME_DATE'].str[:4].astype(int) // 10 * 10)
    all_stats['POSSESSIONS'] = all_stats['DECADE'].map(possessions_by_decade)
    all_stats['PTS(Normalized)'] = 100 * (all_stats['PTS'].astype(int) / all_stats['POSSESSIONS'])

all_stats

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,Player,TEAM,DECADE,POSSESSIONS,PTS(Normalized)
0,22005,977.0,0020500591,2006-01-22,LAL vs. TOR,W,42.0,28.0,46.0,0.609,...,3.0,1.0,81,25.0,0.0,Kobe Bryant,LAL,2000,91,89.010989
1,22016,1626164.0,0021601076,2017-03-24,PHX @ BOS,L,45.0,21.0,40.0,0.525,...,5.0,3.0,70,-6.0,1.0,Devin Booker,PHX,2010,96,72.916667
2,22022,1628378.0,0022200552,2023-01-02,CLE vs. CHI,W,50.0,22.0,34.0,0.647,...,4.0,3.0,71,19.0,1.0,Donovan Mitchell,CLE,2020,99,71.717172
3,22022,203081.0,0022200917,2023-02-26,POR vs. HOU,W,39.0,22.0,38.0,0.579,...,2.0,0.0,71,21.0,1.0,Damian Lillard,POR,2020,99,71.717172
4,22023,203954.0,0022300608,2024-01-22,PHI vs. SAS,W,37.0,24.0,41.0,0.585,...,1.0,2.0,70,11.0,1.0,Joel Embiid,PHI,2020,99,70.707071
5,22023,1629029.0,0022300634,2024-01-26,DAL @ ATL,W,45.0,25.0,33.0,0.758,...,4.0,1.0,73,13.0,1.0,Luka Dončić,DAL,2020,99,73.737374
6,22025,1628389.0,0022500938,2026-03-10,MIA vs. WAS,W,42.0,20.0,43.0,0.465,...,5.0,3.0,83,20.0,1.0,Bam Adebayo,MIA,2020,99,83.838384
7,NaN,NaN,NaN,1960-11-15,LAL vs. NYK,W,NaN,NaN,NaN,0.583,...,NaN,NaN,71,NaN,NaN,Elgin Baylor,LAL,1960,115,61.739130
8,NaN,NaN,NaN,1962-03-02,GSW vs. LAL,L,NaN,NaN,NaN,0.500,...,NaN,NaN,78,NaN,NaN,Wilt Chamberlain,GSW,1960,115,67.826087
9,NaN,NaN,NaN,1963-03-10,GSW vs. CHI,W,NaN,NaN,NaN,0.604,...,NaN,NaN,73,NaN,NaN,Wilt Chamberlain,GSW,1960,115,63.478261
10,NaN,NaN,NaN,1961-12-08,GSW vs. NYK,W,NaN,NaN,NaN,0.571,...,NaN,NaN,100,NaN,NaN,Wilt Chamberlain,GSW,1960,115,86.956522
11,NaN,NaN,NaN,1961-01-13,GSW vs. LAL,L,NaN,NaN,NaN,0.604,...,NaN,NaN,72,NaN,NaN,Wilt Chamberlain,GSW,1960,115,62.608696
12,NaN,NaN,NaN,1962-11-03,GSW vs NYK,W,NaN,NaN,NaN,0.674,...,NaN,NaN,73,NaN,NaN,Wilt Chamberlain,GSW,1960,115,63.478261
13,NaN,NaN,NaN,1962-11-16,GSW vs. SYC,L,NaN,NaN,NaN,0.711,...,NaN,NaN,70,NaN,NaN,Wilt Chamberlain,GSW,1960,115,60.869565
14,NaN,NaN,NaN,1978-04-09,DET vs. DEN,L,NaN,NaN,NaN,0.737,...,NaN,NaN,73,NaN,NaN,David Thompson,DET,1970,106,68.867925
15,NaN,NaN,NaN,1994-04-24,SAS vs. LAC,W,NaN,NaN,NaN,0.634,...,NaN,NaN,71,NaN,NaN,David Robinson,SAS,1990,94,75.531915

## ***Sort the DataFrame by the PTS(Normalized) column***

In [136]:
import polars as pl
import janitor.polars
import polars.selectors as cs
import great_tables as gt
import gt_extras as gte

In [139]:
df = pl.from_pandas(all_stats)

In [149]:
df = (
    df
    .sort("PTS(Normalized)", descending=True)
    .select([
          "TEAM","Player", "GAME_DATE", "WL", "PTS", "PTS(Normalized)"
      ])
)

## ***Create a Great Tables visualization of your findings***

In [194]:
# file path for team logos
img_paths = "https://raw.githubusercontent.com/Henryjean/data/refs/heads/main/square_nba_logos/"

# Generate table
table = (
    gt.GT(df)
    .tab_header(
        title=gt.md("**Greatest NBA Scoring of All Time**"),
        subtitle="Normalized Scoring for Possessions on Average per Decade",
    )
    .cols_label(**{
        "TEAM": "TEAM",
        "Player": "PLAYER", 
        "GAME_DATE": "GAME_DATE",
        "WL": "WL", 
        "PTS": "PTS",
        "PTS(Normalized)": "PTS (Normalized)"
    })

    .fmt_number(columns="PTS(Normalized)", decimals=0)
    .fmt_image(columns = "TEAM", path=img_paths, file_pattern='{}.svg')
    .cols_align(columns = ["PTS"], align = 'right')
    .cols_align(columns = ["PTS(Normalized)"], align = 'center')
    .data_color(
        columns = "PTS(Normalized)",
        domain=[60, 90],
        palette=["orange", "lightgreen", "blue", "purple"],
        na_color="white",
    )
    .tab_options(
        container_width = "100%",
        table_background_color="white",
        row_group_background_color="white",
        table_font_names="Roboto",
        column_labels_font_size="14px",
        column_labels_font_weight="bold", 
        data_row_padding='0px', 
        table_body_hlines_color='transparent', 
        column_labels_border_top_color='black', 
        column_labels_border_top_width="1px",
        column_labels_border_bottom_style='none', 
        heading_border_bottom_style = "none",
        table_body_border_bottom_style="none",
        table_body_border_bottom_color = "white",
        table_border_bottom_style = 'none',
        table_border_top_style = 'none',
        source_notes_border_lr_style = "none"
    )
)

In [195]:
table.save("greatest_nba_scoring.png", scale=3, expand=20)

GT(_tbl_data=shape: (16, 6)
┌──────┬──────────────────┬────────────┬─────┬─────┬─────────────────┐
│ TEAM ┆ Player           ┆ GAME_DATE  ┆ WL  ┆ PTS ┆ PTS(Normalized) │
│ ---  ┆ ---              ┆ ---        ┆ --- ┆ --- ┆ ---             │
│ str  ┆ str              ┆ str        ┆ str ┆ i64 ┆ f64             │
╞══════╪══════════════════╪════════════╪═════╪═════╪═════════════════╡
│ LAL  ┆ Kobe Bryant      ┆ 2006-01-22 ┆ W   ┆ 81  ┆ 89.010989       │
│ GSW  ┆ Wilt Chamberlain ┆ 1961-12-08 ┆ W   ┆ 100 ┆ 86.956522       │
│ MIA  ┆ Bam Adebayo      ┆ 2026-03-10 ┆ W   ┆ 83  ┆ 83.838384       │
│ SAS  ┆ David Robinson   ┆ 1994-04-24 ┆ W   ┆ 71  ┆ 75.531915       │
│ DAL  ┆ Luka Dončić      ┆ 2024-01-26 ┆ W   ┆ 73  ┆ 73.737374       │
│ …    ┆ …                ┆ …          ┆ …   ┆ …   ┆ …               │
│ GSW  ┆ Wilt Chamberlain ┆ 1963-03-10 ┆ W   ┆ 73  ┆ 63.478261       │
│ GSW  ┆ Wilt Chamberlain ┆ 1962-11-03 ┆ W   ┆ 73  ┆ 63.478261       │
│ GSW  ┆ Wilt Chamberlain ┆ 1961-01-13 ┆ L   ┆ 72  ┆ 62.608696       │
│ LAL  ┆ Elgin Baylor     ┆ 1960-11-15 ┆ W   ┆ 71  ┆ 61.73913        │
│ GSW  ┆ Wilt Chamberlain ┆ 1962-11-16 ┆ L   ┆ 70  ┆ 60.869565       │